title: Eunjin<br>Lee # your name (or website title) here
logo: "/images/profile_picture.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><strong>Eunjin Lee</strong><br><br>
  Computer Science major with interests in Machine Learning, Data Analysis, and Recommendation Systems
  <br>
  Email: leee5495@gmail.com<br>
  
theme: jekyll-theme-minimal
google_analytics: UA-178005414-1 # your Google Analytics tracking ID here
