title: Eunjin Lee # your name (or website title) here
logo: "/images/profile_picture.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <strong>이은진</strong>
  <br><br>
  데이터분석, 머신러닝, 추천시스템 등에 관심을 가지고 있는 컴퓨터공학 학생입니다.
  <br><br>
  Contact<br>
  &nbsp;&nbsp;&#128231;: leee5495@gmail.com<br>
  &nbsp;&nbsp;&#128222;: 010-3319-0849<br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
